#  NumPy Basics<hr style = "border:2.5px solid #e22424ff"> </hr>

<b>Amelo Jerow A.</b>
<br>T09 - A</br>

In [146]:
#Importing Lib
import numpy as np
from scipy import stats
from statistics import multimode

In [147]:
my_array = np.array([1,2,3])
my_array

array([1, 2, 3])

In [148]:
np.shape(my_array)

(3,)

# 2D Array

In [149]:
my_array = np.array([
    [1,2,3],
    [1,2,4]
])

my_array

array([[1, 2, 3],
       [1, 2, 4]])

In [150]:
np.shape(my_array)

(2, 3)

In [151]:
t_array = my_array.T
t_array

array([[1, 1],
       [2, 2],
       [3, 4]])

In [152]:
np.shape(t_array)

(3, 2)

# Measures of central tendency

In [153]:
#Jaguar Vs Panthers
resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5,11,10.4, 3, 9.8],
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2 , 9.1 ,9.1, np.nan]
])
np.shape(resistance)


(2, 11)

In [154]:
res_mean = np.nanmean(resistance, axis=1)
print("Jaguar Mean: " + str((res_mean[0]).round(2)))
print("Panthers Mean: " + str((res_mean[1]).round(2)))

Jaguar Mean: 9.4
Panthers Mean: 10.75


In [155]:
res_med = np.nanmedian(resistance, axis=1)
print("Jaguar Median: " + str((res_med[0]).round(2)))
print("Panthers Median: " + str((res_med[1]).round(2)))

Jaguar Median: 9.8
Panthers Median: 9.55


In [156]:
pan_res = resistance[1]
print("Panthers Mode:") 
for i in multimode(pan_res):
    print(f'{i} ohms')


Panthers Mode:
9.1 ohms


In [157]:
jag_res = resistance[0]
print("Jaguar Mode:") 
for i in multimode(jag_res):
    print(f'{i} ohms')

Jaguar Mode:
9.8 ohms
10.4 ohms


# Measures of Variability

In [158]:
#Jaguar Vs Panthers
resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5,11,10.4, 3, 9.8],
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2 , 9.1 ,9.1, np.nan]
])
np.shape(resistance)


(2, 11)

In [159]:
res_max = np.nanmax(resistance, axis=1)
res_min = np.nanmin(resistance, axis=1)

res_range = res_max - res_min
print("Jaguar Range: " + str((res_range[0]).round(2)))
print("Panthers Range: " + str((res_range[1]).round(2)))

Jaguar Range: 8.0
Panthers Range: 10.9


In [160]:
#IQR

res_Q1 = np.nanpercentile(resistance, 25, axis=1)
print("Jaguar Q1: " + str((res_Q1[0]).round(2)))
print("Panthers Q1: " + str((res_Q1[1]).round(2)))


Jaguar Q1: 9.4
Panthers Q1: 9.12


In [161]:
res_Q3 = np.nanpercentile(resistance,75, axis=1)
print("Jaguar Q3: " + str((res_Q3[0]).round(2)))
print("Panthers Q3: " + str((res_Q3[1]).round(2)))


Jaguar Q3: 10.45
Panthers Q3: 10.62


In [162]:
print(f'Jaguar IQR: ' + str((res_Q3[0] - res_Q1[0]).round(2)))
print(f'Panthers IQR: ' + str((res_Q3[1] - res_Q1[1]).round(2)))

Jaguar IQR: 1.05
Panthers IQR: 1.5


In [166]:
res_var = np.nanvar(resistance,ddof = 1, axis=1)
print("Jaguar Variance: " + str((res_var[0]).round(2)))
print("Panthers Variance: " + str((res_var[1]).round(2)))

Jaguar Variance: 4.86
Panthers Variance: 11.08


In [168]:
res_std = np.nanstd(resistance,ddof=1, axis=1)
print("Jaguar Standard Deviation: " + str((res_std[0]).round(2)))
print("Panthers Standard Deviation: " + str((res_std[1]).round( 2)))

Jaguar Standard Deviation: 2.2
Panthers Standard Deviation: 3.33
